GET http://127.0.0.1:3000/auth/ HTTP/1.1


###
POST http://127.0.0.1:3000/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "ankit1",
    "email": "ankitkujat066@google.com",
    "password": "123@abcDEF",
    "confirmPassword": "123@abcDEF"
}

###
POST http://127.0.0.1:3000/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "ankitkujat066@google.com",
    "password": "123@abcDEF"
}

###
DELETE http://127.0.0.1:3000/auth/logout HTTP/1.1


###
POST http://127.0.0.1:3000/auth/update-pass HTTP/1.1
Content-Type: application/json

{
    "oldPassword": "123@abcDEF",
    "password": "123@abcDEF",
    "confirmPassword": "123@abcDEF"
}

###
POST http://127.0.0.1:3000/auth/forget-pass HTTP/1.1
Content-Type: application/json

{
    "email": "ankitkujat066@google.com"
}

###
POST http://127.0.0.1:3000/auth/reset-pass HTTP/1.1
Content-Type: application/json

{
    "tokenId":"609a12fb425bca44d81b9a11",
    "resetPasswordToken": "79faa56c68d0d7adabf9290766ce751f97929dc905e81d2b5c973ea5f0a47032",
    "password": "123@abcDEFG",
    "confirmPassword": "123@abcDEFG"
}